"use client";
import { useEffect, useState } from "react";
import "./advertiser.css";

type Account = { id: string; name: string; balance: number; status: string };
type Campaign = { id: string; name: string; daily_budget: number; spent: number; pacing_mode: string; status: string; ad_count: number; cost: number; impressions: number; clicks: number; conversions: number };
type Creative = { id: string; campaign_id: string; title: string; brand: string; category: string; billing_mode: string; bid: number; status: string; regions: string; devices: string; scenes: string };
const initial = { name: "", brand: "", title: "", dailyBudget: 1000, bid: 20, billingMode: "CPM", pacingMode: "asap", category: "数码科技", regions: ["全国"], devices: ["iOS", "Android"], scenes: ["信息流"] };
const money = (value: number) => `¥ ${Number(value).toLocaleString("zh-CN", { maximumFractionDigits: 2 })}`;

export default function AdvertiserConsole() {
  const [account, setAccount] = useState("adv_demo");
  const [days, setDays] = useState("30");
  const [data, setData] = useState<{ accounts: Account[]; campaigns: Campaign[]; creatives: Creative[] }>({ accounts: [], campaigns: [], creatives: [] });
  const [view, setView] = useState("campaigns");
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState("all");
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const [revision, setRevision] = useState(0);
  const [creating, setCreating] = useState(false);
  const [form, setForm] = useState(initial);
  const [createKey, setCreateKey] = useState("");
  useEffect(() => {
    const controller = new AbortController();
    // Loading tracks the external request lifecycle for account and date changes.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setLoading(true); setError("");
    fetch(`/api/advertiser?account=${encodeURIComponent(account)}&days=${days}`, { signal: controller.signal }).then(async (r) => { const d = await r.json(); if (!r.ok) throw new Error(d.error); return d; }).then(setData).catch((e) => { if (e.name !== "AbortError") setError(e.message); }).finally(() => { if (!controller.signal.aborted) setLoading(false); });
    return () => controller.abort();
  }, [account, days, revision]);
  const selected = data.accounts.find((a) => a.id === account);
  const totals = data.campaigns.reduce((sum, c) => ({ cost: sum.cost + c.cost, impressions: sum.impressions + c.impressions, clicks: sum.clicks + c.clicks, conversions: sum.conversions + c.conversions }), { cost: 0, impressions: 0, clicks: 0, conversions: 0 });
  const rows = data.campaigns.filter((c) => (status === "all" || c.status === status) && `${c.name} ${c.id}`.toLowerCase().includes(query.toLowerCase()));
  async function mutate(path: string, body: object) {
    setBusy(true); setError(""); setNotice("");
    try { const r = await fetch(path, { method: "PATCH", headers: { "content-type": "application/json", "idempotency-key": crypto.randomUUID() }, body: JSON.stringify(body) }); const d = await r.json(); if (!r.ok) throw new Error(d.error); setNotice("修改已保存"); setRevision((v) => v + 1); } catch (e) { setError(e instanceof Error ? e.message : "保存失败"); } finally { setBusy(false); }
  }
  async function create(deliveryStatus: string) {
    setBusy(true); setError("");
    try { const r = await fetch("/api/advertiser", { method: "POST", headers: { "content-type": "application/json", "idempotency-key": createKey }, body: JSON.stringify({ ...form, account, status: deliveryStatus }) }); const d = await r.json(); if (!r.ok) throw new Error(d.error); setCreating(false); setNotice(deliveryStatus === "active" ? "计划已创建并启用，广告已进入投放库存" : "计划已保存为暂停状态，可随时启用"); setRevision((v) => v + 1); } catch (e) { setError(e instanceof Error ? e.message : "创建失败"); } finally { setBusy(false); }
  }
  function exportReport() {
    const cells = (v: unknown) => `"${String(v).replace(/^[=+@-]/, "'$&").replaceAll('"', '""')}"`;
    const csv = [["计划", "状态", "日预算", "消耗", "曝光", "点击", "转化"], ...rows.map((c) => [c.name, c.status, c.daily_budget, c.cost, c.impressions, c.clicks, c.conversions])].map((r) => r.map(cells).join(",")).join("\r\n");
    const url = URL.createObjectURL(new Blob(["\uFEFF", csv], { type: "text/csv;charset=utf-8" })); const a = document.createElement("a"); a.href = url; a.download = `投放报表-${days}天.csv`; a.click(); URL.revokeObjectURL(url);
  }
  const labels: Record<string, string> = { active: "投放中", paused: "已暂停", ended: "已结束" };
  return <section className="advertiser-console">
    <section className="hero module-hero"><div><div className="eyebrow">ADVERTISER / 广告主工作台</div><h1>让每次投放，<em>看得见成效</em></h1><p>管理计划、配置受众与创意，追踪真实曝光、点击和转化。</p></div><button className="run-button" disabled={busy || loading || selected?.status !== "active"} onClick={() => { setForm(initial); setCreateKey(crypto.randomUUID()); setCreating(true); setError(""); }}>＋ 新建投放</button></section>
    <div className="delivery-toolbar"><label>广告主 <select aria-label="广告主" disabled={busy || creating} value={account} onChange={(e) => setAccount(e.target.value)}>{data.accounts.map((a) => <option value={a.id} key={a.id}>{a.name}</option>)}</select></label><span>可用余额 <b>{money(selected?.balance ?? 0)}</b></span><span className="delivery-note">本地演示账户切换</span><label>报表周期 <select value={days} onChange={(e) => setDays(e.target.value)}><option value="7">最近 7 天</option><option value="30">最近 30 天</option></select></label><button className="secondary-button" onClick={() => setRevision((v) => v + 1)}>刷新</button></div>
    {error && <div className="ops-error" role="alert">{error}</div>}{notice && <p className="delivery-success" role="status">{notice}</p>}
    <div className="kpis">{[["实际消耗", money(totals.cost)], ["曝光量", totals.impressions.toLocaleString()], ["点击 / 点击率", `${totals.clicks} / ${totals.impressions ? (totals.clicks / totals.impressions * 100).toFixed(2) : "0.00"}%`], ["转化 / 转化成本", `${totals.conversions} / ${totals.conversions ? money(totals.cost / totals.conversions) : "—"}`]].map(([label, value]) => <article key={label}><span>{label}</span><strong>{loading ? "…" : value}</strong><small>最近 {days} 天 · 有效事件与已扣费账本</small></article>)}</div>
    {creating && <form className="panel delivery-form" onSubmit={(e) => { e.preventDefault(); void create("active"); }}><div className="panel-head"><h2>新建投放</h2><button type="button" className="text-button" disabled={busy} onClick={() => setCreating(false)}>取消</button></div><div className="delivery-form-grid"><fieldset disabled={busy}><legend>01 / 计划与预算</legend><label>计划名称<input required maxLength={100} value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="如：秋季新品推广"/></label><label>每日预算（元）<input required type="number" min="0.01" max="10000000" step="0.01" value={form.dailyBudget} onChange={(e) => setForm({ ...form, dailyBudget: Number(e.target.value) })}/></label><label>投放速度<select value={form.pacingMode} onChange={(e) => setForm({ ...form, pacingMode: e.target.value })}><option value="asap">尽快投放</option><option value="even">匀速投放</option></select></label><label>计费方式<select value={form.billingMode} onChange={(e) => setForm({ ...form, billingMode: e.target.value })}>{["CPM", "CPC", "CPA", "oCPM"].map((m) => <option key={m}>{m}</option>)}</select></label><label>出价（元 / {form.billingMode.includes("CPM") ? "千次曝光" : form.billingMode === "CPC" ? "点击" : "转化"}）<input required type="number" min="0.01" max="10000000" step="0.01" value={form.bid} onChange={(e) => setForm({ ...form, bid: Number(e.target.value) })}/></label></fieldset><fieldset disabled={busy}><legend>02 / 受众与版位</legend>{([ ["regions", "地域", ["全国", "上海", "北京", "杭州", "广州", "深圳"]], ["devices", "设备", ["iOS", "Android"]], ["scenes", "版位", ["信息流", "视频流"]] ] as const).map(([key, label, options]) => <div key={key}><span>{label}</span><div className="delivery-choices">{options.map((value) => <label key={value}><input type="checkbox" checked={form[key].includes(value)} onChange={(e) => setForm({ ...form, [key]: e.target.checked ? [...form[key], value] : form[key].filter((v) => v !== value) })}/>{value}</label>)}</div></div>)}<label>行业 / 兴趣分类<select value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })}>{["数码科技", "旅行", "户外", "餐饮", "汽车", "教育", "生活", "美妆"].map((v) => <option key={v}>{v}</option>)}</select></label></fieldset><fieldset disabled={busy}><legend>03 / 文字创意</legend><label>品牌名称<input required maxLength={100} value={form.brand} onChange={(e) => setForm({ ...form, brand: e.target.value })}/></label><label>广告标题<textarea required maxLength={100} value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })}/></label><div className="delivery-preview"><small>广告 · {form.category}</small><h3>{form.brand || "品牌名称"}</h3><p>{form.title || "你的广告文案将在这里展示"}</p><span>{form.scenes.join(" / ")}</span></div></fieldset></div><div className="delivery-actions"><span>启用后持续投放，直到手动暂停或预算不足。</span><button className="secondary-button" type="button" disabled={busy} onClick={() => void create("paused")}>保存并暂停</button><button className="run-button" disabled={busy}>{busy ? "保存中…" : "创建并启用"}</button></div></form>}
    <article className="panel"><div className="delivery-toolbar"><button className={view === "campaigns" ? "run-button" : "secondary-button"} onClick={() => setView("campaigns")}>投放计划</button><button className={view === "creatives" ? "run-button" : "secondary-button"} onClick={() => setView("creatives")}>创意管理</button><input aria-label="搜索计划" placeholder="搜索计划名称或 ID" value={query} onChange={(e) => setQuery(e.target.value)}/><select aria-label="计划状态" value={status} onChange={(e) => setStatus(e.target.value)}><option value="all">全部计划状态</option>{Object.entries(labels).map(([k, v]) => <option value={k} key={k}>{v}</option>)}</select><button className="secondary-button" disabled={loading} onClick={exportReport}>导出报表</button></div>
    {loading ? <p role="status">正在加载投放数据…</p> : view === "campaigns" ? <div className="delivery-table"><table><thead><tr>{["计划", "状态", "每日预算 / 已占用", "投放速度", "消耗", "曝光 / 点击 / 转化", "操作"].map((v) => <th key={v}>{v}</th>)}</tr></thead><tbody>{rows.map((c) => <tr key={c.id}><td><b>{c.name}</b><small>{c.ad_count} 个创意 · {c.id}</small></td><td>{labels[c.status]}</td><td><input key={`${c.id}-${c.daily_budget}`} aria-label={`${c.name}日预算`} type="number" min="0.01" step="0.01" defaultValue={c.daily_budget} disabled={busy} onBlur={(e) => { const n = Number(e.target.value); if (n !== c.daily_budget) void mutate("/api/campaigns", { id: c.id, dailyBudget: n }); }}/><small>已占用 {money(c.spent)}</small></td><td><select aria-label={`${c.name}投放速度`} value={c.pacing_mode} disabled={busy} onChange={(e) => void mutate("/api/campaigns", { id: c.id, pacingMode: e.target.value })}><option value="asap">尽快</option><option value="even">匀速</option></select></td><td>{money(c.cost)}</td><td>{c.impressions} / {c.clicks} / {c.conversions}</td><td><button className="secondary-button" disabled={busy || c.status === "ended"} onClick={() => void mutate("/api/campaigns", { id: c.id, status: c.status === "active" ? "paused" : "active" })}>{c.status === "active" ? "暂停" : "启用"}</button></td></tr>)}</tbody></table>{!rows.length && <p className="empty-test-state">暂无匹配计划，点击“新建投放”创建第一个计划。</p>}</div> : <div className="delivery-creatives">{data.creatives.filter((a) => rows.some((c) => c.id === a.campaign_id)).map((a) => <div className="delivery-creative" key={a.id}><small>{a.category} · {a.billing_mode}</small><h3>{a.brand}</h3><p>{a.title}</p><small>{[a.regions, a.devices, a.scenes].map((v) => JSON.parse(v).join(" / ")).join(" · ")}</small><label>出价（元）<input key={`${a.id}-${a.bid}`} type="number" min="0.01" step="0.01" defaultValue={a.bid} disabled={busy} onBlur={(e) => { if (Number(e.target.value) !== a.bid) void mutate("/api/inventory", { id: a.id, bid: Number(e.target.value) }); }}/></label><button className="secondary-button" disabled={busy} onClick={() => void mutate("/api/inventory", { id: a.id, status: a.status === "active" ? "paused" : "active" })}>{a.status === "active" ? "暂停创意" : "启用创意"}</button></div>)}{!data.creatives.some((a) => rows.some((c) => c.id === a.campaign_id)) && <p>暂无匹配创意。</p>}</div>}</article>
  </section>;
}
