"use client";
import { useMemo, useState } from "react";
import { interests, runEngine, type RankedAd, type RequestProfile } from "./ad-engine";
import "./workbench.css";
const stages=[{title:"召回",subtitle:"多路策略并行",latency:"8.4 ms"},{title:"过滤",subtitle:"规则与频控",latency:"2.1 ms"},{title:"粗排",subtitle:"轻量模型",latency:"4.7 ms"},{title:"精排",subtitle:"价值预估",latency:"12.6 ms"},{title:"计费",subtitle:"GSP 竞价",latency:"0.8 ms"}];
const Icon=({name}:{name:string})=><span className="icon" aria-hidden="true">{{play:"▶",chevron:"›",refresh:"↻",pulse:"⌁",check:"✓"}[name]}</span>;
export default function AdWorkbench(){
 const [request,setRequest]=useState<RequestProfile>({city:"上海",device:"iOS",scene:"信息流",userId:"u_90382"}); const [active,setActive]=useState(0); const [runId,setRunId]=useState(1); const [running,setRunning]=useState(false);
 const result=useMemo(()=>runEngine(request),[request,runId]); const lists:RankedAd[][]=[result.recalled,result.filtered,result.coarse,result.fine,result.billing?[result.billing]:[]]; const counts=lists.map(x=>x.length);
 const run=()=>{setRunning(true);setActive(0);setRunId(x=>x+1);let s=0;const timer=setInterval(()=>{s++;setActive(Math.min(s,4));if(s>=4){clearInterval(timer);setRunning(false)}},360)};
 return <main className="shell"><header className="topbar"><div className="brand-mark">A</div><div className="brand-copy"><strong>AdFlux</strong><span>广告决策台</span></div><nav><button className="nav-active">请求实验室</button><button>策略配置</button><button>数据监控</button></nav><div className="status"><i/> 系统运行正常</div><button className="run-button" onClick={run} disabled={running}><Icon name={running?"pulse":"play"}/>{running?"决策中…":"运行广告请求"}</button></header>
 <section className="hero"><div><div className="eyebrow">REQUEST LAB / 实时沙盒</div><h1>一次请求，<em>五步决策</em></h1><p>观察一条广告请求如何从候选池中被召回、过滤、排序，最终胜出并完成计费。</p></div><div className="request-card"><span>当前请求</span><strong>req_{(0x8f2a91c7+runId).toString(16)}</strong><small>{request.city} · {request.device} · {request.scene}</small></div></section>
 <section className="pipeline" aria-label="广告决策流程">{stages.map((stage,index)=><button className={`stage ${active===index?"active":""}`} key={stage.title} onClick={()=>setActive(index)}><div className="stage-head"><span>0{index+1}</span><b>{stage.title}</b><i><Icon name="check"/></i></div><strong>{counts[index]}</strong><small>{index===4?"胜出广告":"候选广告"}</small><p>{stage.subtitle}</p><div className="stage-foot">{stage.latency}<Icon name="chevron"/></div></button>)}</section>
 <section className="workspace"><aside><span className="section-label">请求画像</span><h2>这次机会<br/>属于谁？</h2><label>用户 ID<input value={request.userId} onChange={e=>setRequest({...request,userId:e.target.value})}/></label><label>所在城市<select value={request.city} onChange={e=>setRequest({...request,city:e.target.value})}><option>上海</option><option>杭州</option><option>北京</option></select></label><label>设备系统<select value={request.device} onChange={e=>setRequest({...request,device:e.target.value})}><option>iOS</option><option>Android</option></select></label><label>广告场景<select value={request.scene} onChange={e=>setRequest({...request,scene:e.target.value})}><option>信息流</option><option>视频流</option></select></label><div className="interest"><span>兴趣标签</span><div>{interests.map(x=><mark key={x}>{x}</mark>)}</div></div><button className="reset" onClick={()=>setRequest({city:"上海",device:"iOS",scene:"信息流",userId:"u_90382"})}><Icon name="refresh"/> 重置画像</button></aside>
 <div className="stage-detail"><div className="detail-heading"><div><span className="section-label">STAGE 0{active+1}</span><h2>{stages[active].title}{active===0?" · 多路策略":active===4?" · 胜出结果":" · 候选明细"}</h2></div><span className="latency">耗时 {stages[active].latency}</span></div><p>{["基于地域定向、兴趣相似和实时热度并行召回，自动合并去重。","依次执行状态、设备、场景、地域、预算与用户频控规则。","轻量模型综合点击率、质量、出价和兴趣相关度，保留 Top 5。","融合 pCTR、pCVR、质量分和出价预测广告价值，选出 Top 3。","使用广义第二价格机制：胜出者以刚好超过第二名所需的价格计费。"][active]}</p>
 {active===0&&<div className="summary-strip"><div><span>定向召回</span><b>{result.recalled.filter(x=>x.recall.includes("定向召回")).length}</b></div><div><span>兴趣召回</span><b>{result.recalled.filter(x=>x.recall.includes("兴趣召回")).length}</b></div><div><span>热门召回</span><b>{result.recalled.filter(x=>x.recall.includes("热门召回")).length}</b></div></div>}
 {active===4&&result.billing?<Billing ad={result.billing} runner={result.fine[1]}/>:<AdTable ads={lists[active]} stage={active}/>}</div></section>
 <footer><span><i/> 本次链路总耗时 <b>28.6 ms</b></span><span>Demo 数据仅用于算法流程演示</span></footer></main>;
}
function AdTable({ads,stage}:{ads:RankedAd[],stage:number}){return <div className="table-wrap"><table><thead><tr><th>广告</th><th>行业</th><th>{stage===0?"召回通道":stage===1?"状态":"出价"}</th>{stage>=2&&<th>{stage===2?"粗排分":"pCTR / pCVR"}</th>}{stage>=3&&<th>eCPM</th>}</tr></thead><tbody>{ads.map((ad,i)=><tr key={ad.id}><td><div className="ad-cell"><span className="rank">{String(i+1).padStart(2,"0")}</span><i style={{background:ad.color}}>{ad.brand[0]}</i><div><b>{ad.brand}</b><small>{ad.title}</small></div></div></td><td><span className="pill">{ad.category}</span></td><td>{stage===0?<div className="tags">{ad.recall.map(x=><span key={x}>{x}</span>)}</div>:stage===1?<span className="pass">● 通过</span>:<strong>¥ {ad.bid.toFixed(2)}</strong>}</td>{stage>=2&&<td><b>{stage===2?ad.coarseScore:`${(ad.ctr*100).toFixed(1)}% / ${(ad.cvr*100).toFixed(1)}%`}</b></td>}{stage>=3&&<td><b>¥ {ad.ecpm?.toFixed(2)}</b></td>}</tr>)}</tbody></table>{ads.length===0&&<div className="empty">没有广告通过当前阶段，请调整请求画像后重试。</div>}</div>}
function Billing({ad,runner}:{ad:RankedAd,runner?:RankedAd}){return <div className="billing"><div className="winner"><span className="winner-label">WINNING AD / 胜出广告</span><div className="winner-brand"><i style={{background:ad.color}}>{ad.brand[0]}</i><div><h3>{ad.brand}</h3><p>{ad.title}</p></div></div><div className="winner-stats"><div><span>广告出价</span><b>¥ {ad.bid.toFixed(2)}</b></div><div><span>预估 CTR</span><b>{(ad.ctr*100).toFixed(2)}%</b></div><div><span>价值 eCPM</span><b>¥ {ad.ecpm?.toFixed(2)}</b></div></div></div><div className="charge"><span className="section-label">GSP BILLING</span><h3>本次实际计费</h3><strong>¥ {ad.charge?.toFixed(2)} <small>CPM</small></strong><div className="formula"><span>第二名 eCPM</span><b>¥ {runner?.ecpm?.toFixed(2)||"0.00"}</b><i>÷</i><span>胜出者 pCTR</span><b>{(ad.ctr*100).toFixed(2)}%</b><i>+</i><span>最小加价</span><b>¥ 0.01</b></div><p>计费低于广告主出价 ¥ {ad.bid.toFixed(2)}，为广告主节省 <b>{((1-(ad.charge||0)/ad.bid)*100).toFixed(1)}%</b></p></div></div>}
