"use client";

import { interestOptions, interests, type EngineResult, type RankedAd, type RequestProfile } from "./ad-engine";

export type DecisionDiagnostics = { timingsMs: Record<string, number>; recallChannels: Record<string, number>; filterReasons: Record<string, number> };
type Delivery = { filled: boolean; noFillReason: string | null; budgetRejectedCount: number };
const stages = [{ title: "召回", subtitle: "多路策略并行", key: "recall" }, { title: "过滤", subtitle: "规则与频控", key: "filter" }, { title: "粗排", subtitle: "轻量模型", key: "coarse" }, { title: "精排", subtitle: "价值预估", key: "fine" }, { title: "计费", subtitle: "拍卖清算", key: "billing" }];

export default function DecisionLab({ request, setRequest, result, counts, active, setActive, requestId, error, diagnostics, delivery }: { request: RequestProfile; setRequest: (value: RequestProfile) => void; result: EngineResult; counts: number[]; active: number; setActive: (value: number) => void; requestId: string; error: string; diagnostics?: DecisionDiagnostics; delivery?: Delivery }) {
  const lists: RankedAd[][] = [result.recalled, result.filtered, result.coarse, result.fine, result.billing ? [result.billing] : []];
  const noFill: Record<string, string> = { no_ranked_candidate: "没有通过排序的候选", budget_unavailable: "候选预算不可用", below_floor: "候选低于广告位底价" };
  return <><section className="hero"><div><div className="eyebrow">REQUEST LAB / 服务端决策</div><h1>一次请求，<em>五步决策</em></h1><p>由服务端从 D1 加载广告、用户曝光频次和生产配置，完成决策并持久化请求记录。</p></div><div className={`request-card ${error ? "request-error" : ""}`}><span>服务端请求</span><strong>{requestId}</strong><small>{error || `${request.city} · ${request.device} · ${request.scene}`}</small></div></section>
    <section className="pipeline">{stages.map((stage, index) => <button className={`stage ${active === index ? "active" : ""}`} key={stage.title} onClick={() => setActive(index)}><div className="stage-head"><span>0{index + 1}</span><b>{stage.title}</b><i>✓</i></div><strong>{counts[index]}</strong><small>{index === 4 ? "胜出广告" : "候选广告"}</small><p>{stage.subtitle}</p><div className="stage-foot">{diagnostics ? `${(diagnostics.timingsMs[stage.key] ?? 0).toFixed(3)} ms` : "等待请求"}<span>›</span></div></button>)}</section>
    {diagnostics && <section className="decision-diagnostics"><div><span>总耗时</span><b>{diagnostics.timingsMs.total.toFixed(3)} ms</b></div>{Object.entries(diagnostics.filterReasons).slice(0, 4).map(([reason, count]) => <div key={reason}><span>{reason}</span><b>{count}</b></div>)}{delivery && <div className={delivery.filled ? "diagnostic-pass" : "diagnostic-fail"}><span>投放结果</span><b>{delivery.filled ? "已填充" : noFill[delivery.noFillReason ?? ""] ?? "未填充"}</b></div>}</section>}
    <section className="workspace"><Profile request={request} setRequest={setRequest}/><div className="stage-detail"><div className="detail-heading"><div><span className="section-label">STAGE 0{active + 1}</span><h2>{stages[active].title} · {active === 0 ? "多路策略" : active === 4 ? "胜出结果" : "候选明细"}</h2></div><span className="latency">{diagnostics ? `实际耗时 ${(diagnostics.timingsMs[stages[active].key] ?? 0).toFixed(3)} ms` : "本地预览"}</span></div><p>{["地域、兴趣与热门三路并行召回，自动合并去重。", "执行状态、设备、场景、地域、预算和用户级频控。", "综合点击率、质量、出价和兴趣相关度保留 Top K。", "融合 pCTR、pCVR、质量分和出价预测价值。", "按照广告位配置执行 GSP 或一价拍卖并预占预算。"][active]}</p>{active === 0 && <div className="summary-strip">{["定向召回", "兴趣召回", "热门召回"].map((channel) => <div key={channel}><span>{channel}</span><b>{diagnostics?.recallChannels[channel] ?? result.recalled.filter((ad) => ad.recall.includes(channel)).length}</b></div>)}</div>}{active === 4 && result.billing ? <Billing ad={result.billing} runner={result.fine[1]}/> : <AdTable rows={lists[active]} stage={active}/>}</div></section></>;
}

function Profile({ request, setRequest }: { request: RequestProfile; setRequest: (value: RequestProfile) => void }) { const selected = request.interests ?? interests; const toggle = (value: string) => setRequest({ ...request, interests: selected.includes(value) ? selected.filter((item) => item !== value) : [...selected, value] }); return <aside><span className="section-label">请求画像</span><h2>这次机会<br/>属于谁？</h2><label>用户 ID<input value={request.userId} onChange={(event) => setRequest({ ...request, userId: event.target.value })}/></label>{[["所在城市", "city", ["上海", "杭州", "北京", "广州", "深圳"]], ["设备系统", "device", ["iOS", "Android"]], ["广告场景", "scene", ["信息流", "视频流"]]].map(([label, key, options]) => <label key={key as string}>{label as string}<select value={request[key as keyof RequestProfile] as string} onChange={(event) => setRequest({ ...request, [key as string]: event.target.value })}>{(options as string[]).map((option) => <option key={option}>{option}</option>)}</select></label>)}<div className="interest"><span>兴趣标签 · 已选 {selected.length}</span><div>{interestOptions.map((item) => <button type="button" className={selected.includes(item) ? "selected" : ""} aria-pressed={selected.includes(item)} onClick={() => toggle(item)} key={item}>{item}</button>)}</div><button type="button" className="clear-interests" onClick={() => setRequest({ ...request, interests: [] })}>清空兴趣</button></div></aside>; }

function AdTable({ rows, stage }: { rows: RankedAd[]; stage: number }) { const shown = rows.slice(0, 12); return <div className="table-wrap"><table><thead><tr><th>广告</th><th>行业</th>{stage === 3 && <th>计费模式</th>}<th>{stage === 0 ? "召回通道" : stage === 1 ? "状态" : "出价"}</th>{stage >= 2 && <th>{stage === 2 ? "粗排分" : "pCTR / pCVR"}</th>}{stage >= 3 && <th>价值 eCPM</th>}</tr></thead><tbody>{shown.map((ad, index) => <tr key={ad.id}><td><div className="ad-cell"><span className="rank">{String(index + 1).padStart(2, "0")}</span><i style={{ background: ad.color }}>{ad.brand[0]}</i><div><b>{ad.brand}</b><small>{ad.title}</small></div></div></td><td><span className="pill">{ad.category}</span></td>{stage === 3 && <td><span className={`billing-mode mode-${ad.billingMode.toLowerCase()}`}>{ad.billingMode}</span></td>}<td>{stage === 0 ? <div className="tags">{ad.recall.map((tag) => <span key={tag}>{tag}</span>)}</div> : stage === 1 ? <span className="pass">● 通过</span> : <strong>¥ {ad.bid.toFixed(2)} <small>/{ad.billingMode === "CPM" ? "千次" : ad.billingMode === "CPC" ? "点击" : "转化"}</small></strong>}</td>{stage >= 2 && <td><b>{stage === 2 ? ad.coarseScore : `${(ad.ctr * 100).toFixed(1)}% / ${(ad.cvr * 100).toFixed(1)}%`}</b></td>}{stage >= 3 && <td><b>¥ {ad.ecpm?.toFixed(2)}</b></td>}</tr>)}</tbody></table>{rows.length > shown.length && <div className="more">显示前 {shown.length} 条 · 共 {rows.length} 条候选</div>}</div>; }

function Billing({ ad, runner }: { ad: RankedAd; runner?: RankedAd }) { return <div className="billing"><div className="winner"><span className="winner-label">WINNING AD / 胜出广告</span><div className="winner-brand"><i style={{ background: ad.color }}>{ad.brand[0]}</i><div><h3>{ad.brand}</h3><p>{ad.title}</p></div></div><div className="winner-stats"><div><span>广告出价</span><b>¥ {ad.bid.toFixed(2)}</b></div><div><span>预估 CTR</span><b>{(ad.ctr * 100).toFixed(2)}%</b></div><div><span>价值 eCPM</span><b>¥ {ad.ecpm?.toFixed(2)}</b></div></div></div><div className="charge"><span className="section-label">AUCTION BILLING</span><h3>本次清算价格</h3><strong>¥ {ad.charge?.toFixed(4)} <small>{ad.billingMode}</small></strong><div className="formula"><span>第二名 eCPM</span><b>¥ {runner?.ecpm?.toFixed(2) ?? "—"}</b><span>计费模式</span><b>{ad.billingMode}</b></div></div></div>; }
